title: My blog
author: Ruta
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Awesome blog about me
theme: minima

# social links
twitter_username: rreisoh # DO NOT include the @ character, or else the build will fail!
github_username:  RReiso # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
